### ISSUE TITLE
Scrolling whlie dragging the thumb isn't continuous

### ISSUE THREAD

**Issue by zhanghai** [timusus/RecyclerView-FastScroll#103]
On the contrary, it jumps with small increments.

In v1.0.18 the scrolling while dragging is still continuous and beautiful.

I suspect [#83](https://github.com/timusus/RecyclerView-FastScroll/pull/83/files#diff-0c1e8268f4f82b902f526173796ba312R214) is causing this regression, as it makes the recycler view skip scrolling until the accumulated drag distance exceeds touch slop. Touch slop is most often used for distinguishing a click from drag, but not for the process within dragging itself, so I don't think it should be the intended behavior.

**Comment by goldy1992** [comment]
Removing the `mTouchSlop`  comparison removes the problem for dragging as you correctly predicted @zhanghai .

However, when running the sample app, the scroll bar for normal scrolling still seems to be jumping in small increments; this I believe is due to the amount of time spent in the main thread, as the image is not cached

**Comment by goldy1992** [comment]
@zhanghai @timusus please see the [pull request for issue 103](https://github.com/timusus/RecyclerView-FastScroll/pull/105)
