### ISSUE TITLE
Different Viewtypes

### ISSUE THREAD

**Issue by ghost** [timusus/RecyclerView-FastScroll#42]
I am using 2 different viewtypes (a textview and a cardview) for the recyclerview. When the type is changing in the recyclerview while scrolling it is lagging (scroll bar is jumping up and down like crazy).
In getSectionedName I'm is always returning "A" 
Any fixes?

**Comment by timusus** [comment]
Currently this library assumes all items are of equal height. This limitation is brought about because there's no non-trivial way to determine what the total height of all the views in the RecyclerView will be, so then there's no way to determine what the current position of the FastScroll should be.

**Comment by timusus** [comment]
Edit: This is now supported using the `MeasurableAdapter` interface (see Readme). Your `RecyclerViewAdapter` is still required to have `ViewHolders` with determinate heights. In other words, you'll need to be able to tell Adapter what the height of a specific `ViewHolder` is, before it is drawn on screen.
