### ISSUE TITLE
Changing width and height of scroll bar

### ISSUE THREAD

**Issue by Nischitha-S** [timusus/RecyclerView-FastScroll#67]
iam new to android and in this iam unable to change the width and height of the scroll bar.please help me to do thatand remaining all working properly

**Comment by G00fY2** [comment]
At the moment the sizes are the same Google is using for their FastScroll implementations. If you like to change those you properly need to fork this library and change `mThumbHeight`, `mWidth`  in the `FastScroller.java` class.

If you mean the offset of the scrolbar in the top and the bottom you find my pull request here: #59
@timusus just has not released an update since my PR.

**Comment by timusus** [comment]
This will require forking, as @G00fY2 says. If you'd like to make a PR after forking, feel free.
