### ISSUE TITLE
Recyclerview inside NestedScrollView.

### ISSUE THREAD

**Issue by AhmadullahSaikat** [timusus/RecyclerView-FastScroll#71]
Recyclerview inside NestedScrollView. fastScroll not showing.

**Comment by timusus** [comment]
I've had a look into this..

When you nest a `RecyclerView` inside a `NestedScrollView`, the `RecyclerViews` children are all created at once (rather than as you scroll). This is ill-advised in my opinion, as you lose the benefits of 'recycling' which come with the `RecyclerView`.

In turn, the `RecyclerView's` internal `draw(Canvas c)` is not called as you scroll, which is the trigger for us drawing the fast scroll on the screen.

There's definitely no simple workaround for this. I would recommend you don't nest `RecyclerView` inside of `ScrollView`, but instead use a different/separate `ViewTypes`/`ViewHolders` for the views you wish to be scrolled with your `RecyclerView's` content.

I'm closing this issue. This feature is not supported by this library.
