### ISSUE TITLE
Scroll not working in Nested Scroll view

### ISSUE THREAD

**Issue by rajan051** [timusus/RecyclerView-FastScroll#92]
I have one nested scroll view with two recycle view,one vertical & one horizontal. in vertical recycle view i implemented this library. but it wont work.

**Comment by timusus** [comment]
RecyclerView-FastScroll is not supported inside NestedScrollViews. When you place a RecyclerView inside a NestedScrollView, the RecyclerView's height expands to the height of all of its items. When you scroll, you're not really scrolling the RecyclerView anymore, you're scrolling the NestedScrollView. This makes it impossible to determine what the position of the FastScroll thumb should be (how far the RecyclerView has scrolled, since technically it hasn't scrolled at all).
